# Generated by Django 4.2.1 on 2023-07-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, max_length=60, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('num', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('num', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('num', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.category')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.marque')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='code_serie',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.produit')),
            ],
        ),
    ]
