# Generated by Django 4.2.1 on 2023-07-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='num',
        ),
        migrations.RemoveField(
            model_name='marque',
            name='num',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code_serie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marque',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='code_serie',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='code_serie',
            name='produit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scanner.produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marque',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scanner.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scanner.marque'),
            preserve_default=False,
        ),
    ]
